[build]
builder = "NIXPACKS"
buildCommand = "npm install --legacy-peer-deps"

[deploy]
startCommand = "node web.js"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
